### PR TITLE
Trivial tidying

### PR DESCRIPTION
**Pull request by atomgardner**
As promised, here are some real urgent fixes.

### CODE REVIEW

**Comment by liamzebedee** [comment]
Hahhahaha.

Can you explain more @atomgardner? It looks like formatting changes though from my view of the git diff I can't see what's changed? Is it tabs to spaces?

**Comment by atomgardner** [comment]
The log makes it clear what's changed. And https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log does a great job justifying the change.

**Comment by liamzebedee** [comment]
Ahh right. Is there an automated tool we can use to run this? fmt/lint? otherwise I don't see it as cost-efficient since I'm never going to remember to insert newlines.

**Comment by atomgardner** [comment]
Git points this out to you. Github points it out sometimes too: image

**Pull request closed without merging**
